---
title: "My first attempt to 30 day chart challenge"
author: "birasafab"
date: "4/4/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(WDI)
```

# searching for the data 
```{r}
WDIsearch("population") %>% 
  View()
```




# loading map data
```{r}
library(fuzzyjoin)
library(ggthemes)

world_data<- map_data("world") %>% 
  as_tibble() %>% 
  regex_left_join(maps::iso3166 %>%
                    select(mapname, country_code = a2), c(region = "mapname")) %>% 
  filter(region != "Antarctica")

# 
# # lat and long for adding to map
# world_data %>% 
#   filter(region %in% c("Rwanda", "Burundi", "Kenya", "Uganda", "Tanzania", "South Sudan")) %>% 
#   ggplot()+
#   geom_polygon(aes(long,lat, group = group), fill = "yellow", color = "red")+
#   theme_map()+
#   geom_point(data = data, aes(x=long,y=lat,size = pop))

# 
# data = tibble(
#   country = c("Rwanda", "Burundi", "Tanzania", "Kenya", "Uganda", "South Sudan"),
#   population = c(12,14,34,35,42,28)
# )


# final  = world_data %>% 
#   filter(region %in% c("Rwanda", "Burundi", "Kenya", "Uganda", "Tanzania", "South Sudan")) %>% 
#   group_by(mapname) %>% 
#   mutate(lat_m = mean(lat),
#          long_m = mean(long)) %>% 
#   left_join(data, by = c("region" = "country"))


# # final plot
# 
# final %>% 
#   ggplot()+
#   geom_polygon(aes(long, lat, group = group, fill = region), color = "red")+
#   geom_point(aes(x = long_m, y = lat_m, size = population), color = "yellow")+
#   theme_map()+
#   geom_label(aes(x = long_m, y = lat_m,label = region), hjust = 1.22)
  
```


#loading the data of interest (EAC countries related data)
```{r}
# rwanda data
eac_data = WDI(country = c("RW", "KE", "BDI", "UG", "TZ","SS","CD"), indicator = "SP.POP.TOTL", start = 2020, end = 2020)

eac_data = eac_data %>% 
  rename(population = `SP.POP.TOTL`)


# combining the two resultant datasets
final = world_data %>% 
  filter(country_code %in% c("RW", "KE", "BI", "UG", "TZ","SS", "CD")) %>% 
  group_by(mapname) %>% 
  mutate(lat_m = mean(lat),
         long_m = mean(long)) %>% 
  left_join(eac_data, by = c("country_code" = "iso2c"))
```


# Final plot
```{r}
final %>%
  ggplot()+
  geom_polygon(aes(long, lat, group = group, fill = mapname))+
  theme_map()+
  geom_point(aes(x = long_m, y = lat_m, size = population))+
  geom_label(aes(x = long_m, y = lat_m,label = paste0(region,", ", round(population/1000000,2)), hjust = 1.2, fill = mapname))+
  labs(
    title = "Guess How big is the EAC market with addition of the DRC?",
    subtitle = "East African Community's market is growing with addition of almost 90 million citizens from DR Congo in the family to mark the 7th country of the entire community. \nBelow is the status of each country's population size as of 2020, figures are in million # with 2 decimals round.",
    caption = "Plot by @birasafab | Data from World bank accessed through WDI | #30DayChartChallenge"
  )+
  theme(
    legend.position = "none",
    panel.background = element_rect(fill = "black"),
    plot.background = element_rect(fill = "#a8e3e7" ),
    plot.title = element_text(size = 22)
  )
```


# Test on how to use map data and bubbles chart
```{r}
# uk = map_data("world") %>% 
#   filter(region == "Rwanda")
# 
# # data to be mapped
# 
# data = maps::world.cities %>% 
#   filter(country.etc =="Rwanda")
# 
# # creating uk map
# 
# uk %>% 
#   ggplot()+
#   geom_polygon(aes(x = long,y = lat, group = group))+
#   geom_point(data = data, aes(x = long, y = lat,size = pop, color=name ))

```

